### ISSUE TITLE
Problema na consulta de produto inexistente

### ISSUE THREAD

**Issue by LeandroHR** [LeandroHR/Programacao1_Trab1#1]
Linha 169, as condições após o else não estão funcionando se o produto não esta cadastrado, antes da alteração trazia uma a resposta uma vez para cada vez que não achasse.

**Comment by LeandroHR** [comment]
Feito ajuste em uma das variáveis usadas no teste, testar programa.

**Comment by Monjakeys** [comment]
Resolvido
